### ISSUE TITLE
使用Rotated Gaussian Kernel的问题

### ISSUE THREAD

**Issue by JinYuannn** [zf020114/CHPDet#4]
您好，感谢您的工作！我使用了这个项目sample/multi_pose.py中的画heatmap的方法替换了原centernet中的相应部分（其它不变）训练我自己的数据集（99张图片，每张图片1个object），画出了带角度的椭圆高斯核，但在训练中发现：
1. 训练损失和验证损失都可以下降到比较小（140 epoch，hm loss ~ 0.0015）
2. 但是模型输出的heatmap是检测不到任何东西的，heatmap最大值在0.013左右
请问能给我一些debug的建议吗？是损失函数的问题吗？我检查了损失函数，好像这个项目的损失函数和centernet是一样的

**Comment by zf020114** [comment]
你好，我觉得你可以检查一下你的代码，按理说损失函数没问题，那么应该训练部分问题不大。你可以看一下推理部分，是不是因为没有在最后加上sigmod（）函数。导致最大在0.0013左右。你还可以在训练阶段可视化一下得到的heatmap，看看问题到底是在训练阶段还是在推理阶段。

**Comment by JinYuannn** [comment]
谢谢您的回复，确实是我draw heatmap时有问题，已修改。并且我使用rotated gs kernel后测试结果miou提高了0.1，感谢。
