### ISSUE TITLE
关于您公开的DLA-34_OIM权重多出的两个参数问题

### ISSUE THREAD

**Issue by 1667553930** [zf020114/CHPDet#6]
首先感谢您公开了代码与数据集。我在复现您代码的过程中发现关于DLA-34_OIM权重，它要比网络多出两个参数。“Drop parameter base.fc.weight”和“Drop parameter base.fc.bias”。以至于我无法复原到您论文中所述的精度。我想请问下这是什么原因

**Comment by zf020114** [comment]
谢谢你关注我的工作。与你提到的问题，我在运行的时候没有遇到过。我想可能的原因是不是你在运行的时候配置文件设置的骨干网络，你看那个字段是不是设置有问题。目前我正在写毕业论文，可能也没有时间去详细的复现错误。这个算法只是对于比较细长的旋转的舰船检测比较有优势。如果你需要的是通用的旋转目标检测算法。可以建议看一下商汤出的mmrotate。发自我的手机-------- 原始邮件 --------发件人： 1667553930 ***@***.***>日期： 2022年8月27日周六 中午11:58收件人： zf020114/CHPDet ***@***.***>抄送： Subscribed ***@***.***>主    题： [zf020114/CHPDet] 关于您公开的DLA-34_OIM权重多出的两个参数问题 (Issue #6)

首先感谢您公开了代码与数据集。我在复现您代码的过程中发现关于DLA-34_OIM权重，它要比网络多出两个参数。“Drop parameter base.fc.weight”和“Drop parameter base.fc.bias”。以至于我无法复原到您论文中所述的精度。我想请问下这是什么原因

**Comment by 1667553930** [comment]
Dear author:上述问题是真的存在于您发布的“dlaarf_34”权重。它的参数显示为422，但网络所需参数为422。不过，这个问题似乎并不影响最终精度。在您公布的实验环境所需：torch 1.4，数据集：FGSD2021中测试得到的“07_metric”:0.8714887067775938。这与您发布的文章结果十分接近。事实上在复现过程中的困难原非如此，我几乎阅读完您所有的代码才获得这一结果。这一切困难除了在30显卡的时代去获得一张20的显卡用来搭建环境外，还包括图像的预处理（切片与旋转），这需要反复阅读您的论文以及代码去揣摩您的用意。但这一切是值得的，您的论文给了我很多启发。再次谢谢您的开源。

**Comment by zf020114** [comment]
再次感谢你关注我的工作。谢谢。发自我的手机-------- 原始邮件 --------发件人： 1667553930 ***@***.***>日期： 2022年8月27日周六 下午2:48收件人： zf020114/CHPDet ***@***.***>抄送： zf020114 ***@***.***>, Comment ***@***.***>主    题： Re: [zf020114/CHPDet] 关于您公开的DLA-34_OIM权重多出的两个参数问题 (Issue #6)
Dear author:上述问题是真的存在于您发布的“dlaarf_34”权重。它的参数显示为422，但网络所需参数为422。不过，这个问题似乎并不影响最终精度。在您公布的实验环境所需：torch 1.4，数据集：FGSD2021中测试得到的“07_metric”:0.8714887067775938。这与您发布的文章结果十分接近。事实上在复现过程中的困难原非如此，我几乎阅读完您所有的代码才获得这一结果。这一切困难除了在30显卡的时代去获得一张20的显卡用来搭建环境外，还包括图像的预处理（切片与旋转），这需要反复阅读您的论文以及代码去揣摩您的用意。但这一切是值得的，您的论文给了我很多启发。再次谢谢您的开源。
